// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | ArticleListSlice
  | ImageAndTextSlice
  | CallToActionSlice
  | RichTextParagraphSlice
  | ServicesSlice
  | AccordionSlice
  | HeroSlice
  | TitleDateAndAuthorSlice
  | AdvisorProfileCardSlice
  | FullPageImageSlice
  | FeaturesSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | AdvisorProfileCardSlice
  | AccordionSlice
  | ServicesSlice
  | RichTextParagraphSlice
  | TitleDateAndAuthorSlice
  | ImageAndTextSlice
  | CallToActionSlice
  | FeaturesSlice
  | FullPageImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Header Navigation*
 */
export interface SettingsDocumentDataHeaderNavigationItem {
  /**
   * Label field in *Settings → Header Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Header Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Footer Navigation*
 */
export interface SettingsDocumentDataFooterNavigationItem {
  /**
   * Label field in *Settings → Footer Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Footer Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Label field in *Settings → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *Settings → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Site Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Site Logo Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  site_logo_link: prismic.LinkField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Contact Email field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact Phone No field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_phone_no
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_phone_no: prismic.KeyTextField;

  /**
   * Contact Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_address: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Header Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataHeaderNavigationItem>
  >;

  /**
   * Footer Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavigationItem>
  >;

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *Accordion → Primary*
 */
export interface AccordionSliceDefaultPrimary {
  /**
   * Title field in *Accordion → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Primary content in *Accordion → Items*
 */
export interface AccordionSliceDefaultItem {
  /**
   * Title field in *Accordion → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *Accordion → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Accordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSliceDefaultPrimary>,
  Simplify<AccordionSliceDefaultItem>
>;

/**
 * Slice variation for *Accordion*
 */
type AccordionSliceVariation = AccordionSliceDefault;

/**
 * Accordion Shared Slice
 *
 * - **API ID**: `accordion`
 * - **Description**: Accordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordionSlice = prismic.SharedSlice<
  "accordion",
  AccordionSliceVariation
>;

/**
 * Primary content in *AdvisorProfileCard → Primary*
 */
export interface AdvisorProfileCardSliceDefaultPrimary {
  /**
   * Title field in *AdvisorProfileCard → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * View All Link field in *AdvisorProfileCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.primary.view_all_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  view_all_link: prismic.LinkField;
}

/**
 * Primary content in *AdvisorProfileCard → Items*
 */
export interface AdvisorProfileCardSliceDefaultItem {
  /**
   * Name field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Text field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Profile Image field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].profile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;

  /**
   * Youtube Link field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].youtube_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_link: prismic.LinkField;

  /**
   * Linkedin Link field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].linkedin_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField;

  /**
   * Facebook Link field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].facebook_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook_link: prismic.LinkField;

  /**
   * View Btn Link field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].view_btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  view_btn_link: prismic.LinkField;

  /**
   * Role field in *AdvisorProfileCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advisor_profile_card.items[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.RichTextField;
}

/**
 * Default variation for AdvisorProfileCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvisorProfileCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdvisorProfileCardSliceDefaultPrimary>,
  Simplify<AdvisorProfileCardSliceDefaultItem>
>;

/**
 * Slice variation for *AdvisorProfileCard*
 */
type AdvisorProfileCardSliceVariation = AdvisorProfileCardSliceDefault;

/**
 * AdvisorProfileCard Shared Slice
 *
 * - **API ID**: `advisor_profile_card`
 * - **Description**: AdvisorProfileCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvisorProfileCardSlice = prismic.SharedSlice<
  "advisor_profile_card",
  AdvisorProfileCardSliceVariation
>;

/**
 * Primary content in *ArticleList → Primary*
 */
export interface ArticleListSliceDefaultPrimary {
  /**
   * Title field in *ArticleList → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *ArticleList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link field in *ArticleList → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *ArticleList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Primary content in *ArticleList → Items*
 */
export interface ArticleListSliceDefaultItem {
  /**
   * Article Link field in *ArticleList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].article_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article_link: prismic.LinkField;

  /**
   * Article Banner Image field in *ArticleList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].article_banner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  article_banner_image: prismic.ImageField<never>;

  /**
   * Title Tag  field in *ArticleList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].title_tag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_tag: prismic.RichTextField;

  /**
   * Article Title field in *ArticleList → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].article_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_title: prismic.TitleField;

  /**
   * Article Text field in *ArticleList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].article_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  article_text: prismic.RichTextField;

  /**
   * Author Image field in *ArticleList → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].author_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  author_image: prismic.ImageField<never>;

  /**
   * Author Name field in *ArticleList → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].author_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author_name: prismic.RichTextField;

  /**
   * Date Published field in *ArticleList → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].date_published
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_published: prismic.DateField;

  /**
   * Reading Time field in *ArticleList → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: article_list.items[].reading_time
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  reading_time: prismic.NumberField;
}

/**
 * Default variation for ArticleList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleListSliceDefaultPrimary>,
  Simplify<ArticleListSliceDefaultItem>
>;

/**
 * Slice variation for *ArticleList*
 */
type ArticleListSliceVariation = ArticleListSliceDefault;

/**
 * ArticleList Shared Slice
 *
 * - **API ID**: `article_list`
 * - **Description**: ArticleList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleListSlice = prismic.SharedSlice<
  "article_list",
  ArticleListSliceVariation
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * CTA Image field in *CallToAction → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_image: prismic.ImageField<never>;

  /**
   * CTA Ttile field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_ttile
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_ttile: prismic.TitleField;

  /**
   * CTA Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_text: prismic.RichTextField;

  /**
   * CTA Btn Title 1 field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_btn_title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_btn_title_1: prismic.KeyTextField;

  /**
   * CTA Btn Link 1 field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_btn_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_btn_link_1: prismic.LinkField;

  /**
   * CTA Btn Title 2 field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_btn_title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_btn_title_2: prismic.KeyTextField;

  /**
   * CTA Btn Link 2 field in *CallToAction → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_btn_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_btn_link_2: prismic.LinkField;

  /**
   * CTA Announcement Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.cta_announcement_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_announcement_text: prismic.RichTextField;
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceDefaultItem {
  /**
   * CTA Advisor Image field in *CallToAction → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].cta_advisor_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cta_advisor_image: prismic.ImageField<never>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  Simplify<CallToActionSliceDefaultItem>
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Feature Block Title field in *Features → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_block_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_block_title: prismic.TitleField;

  /**
   * Feature Block Text field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_block_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_block_text: prismic.RichTextField;

  /**
   * Feature Block Tag field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.feature_block_tag
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_block_tag: prismic.RichTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Feature Title field in *Features → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_title: prismic.TitleField;

  /**
   * Feature text field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_text: prismic.RichTextField;

  /**
   * Feature Btn Link field in *Features → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature_btn_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  feature_btn_link: prismic.LinkField;

  /**
   * Feature Btn Text field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature_btn_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feature_btn_text: prismic.KeyTextField;

  /**
   * Feature Image field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_image: prismic.ImageField<never>;

  /**
   * Feature Icon field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].feature_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  feature_icon: prismic.ImageField<never>;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *FullPageImage → Primary*
 */
export interface FullPageImageSliceDefaultPrimary {
  /**
   * Image field in *FullPageImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_page_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for FullPageImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullPageImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullPageImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullPageImage*
 */
type FullPageImageSliceVariation = FullPageImageSliceDefault;

/**
 * FullPageImage Shared Slice
 *
 * - **API ID**: `full_page_image`
 * - **Description**: FullPageImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullPageImageSlice = prismic.SharedSlice<
  "full_page_image",
  FullPageImageSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Text 1 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_1: prismic.KeyTextField;

  /**
   * Button Link 1 field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_1: prismic.LinkField;

  /**
   * Button Link 2 field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_2: prismic.LinkField;

  /**
   * Button Text 2 field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text_2: prismic.KeyTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video Link field in *Hero → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.video_link
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  video_link: prismic.EmbedField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageAndText → Primary*
 */
export interface ImageAndTextSliceDefaultPrimary {
  /**
   * Title field in *ImageAndText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *ImageAndText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link field in *ImageAndText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *ImageAndText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Text Color field in *ImageAndText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Image field in *ImageAndText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageAndText → Primary*
 */
export interface ImageAndTextSliceImageAndTextRightPrimary {
  /**
   * Title field in *ImageAndText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *ImageAndText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link field in *ImageAndText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *ImageAndText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Text Color field in *ImageAndText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Image field in *ImageAndText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * ImageAndText-Right variation for ImageAndText Slice
 *
 * - **API ID**: `imageAndTextRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSliceImageAndTextRight = prismic.SharedSliceVariation<
  "imageAndTextRight",
  Simplify<ImageAndTextSliceImageAndTextRightPrimary>,
  never
>;

/**
 * Primary content in *ImageAndText → Primary*
 */
export interface ImageAndTextSliceImageAndTextLeftPrimary {
  /**
   * Title field in *ImageAndText → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *ImageAndText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Link field in *ImageAndText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *ImageAndText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Text Color field in *ImageAndText → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.text_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_color: prismic.ColorField;

  /**
   * Image field in *ImageAndText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * ImageAndText-Left variation for ImageAndText Slice
 *
 * - **API ID**: `imageAndTextLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSliceImageAndTextLeft = prismic.SharedSliceVariation<
  "imageAndTextLeft",
  Simplify<ImageAndTextSliceImageAndTextLeftPrimary>,
  never
>;

/**
 * Slice variation for *ImageAndText*
 */
type ImageAndTextSliceVariation =
  | ImageAndTextSliceDefault
  | ImageAndTextSliceImageAndTextRight
  | ImageAndTextSliceImageAndTextLeft;

/**
 * ImageAndText Shared Slice
 *
 * - **API ID**: `image_and_text`
 * - **Description**: ImageAndText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSlice = prismic.SharedSlice<
  "image_and_text",
  ImageAndTextSliceVariation
>;

/**
 * Primary content in *RichTextParagraph → Primary*
 */
export interface RichTextParagraphSliceDefaultPrimary {
  /**
   * Text field in *RichTextParagraph → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_paragraph.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for RichTextParagraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextParagraphSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextParagraphSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextParagraph*
 */
type RichTextParagraphSliceVariation = RichTextParagraphSliceDefault;

/**
 * RichTextParagraph Shared Slice
 *
 * - **API ID**: `rich_text_paragraph`
 * - **Description**: RichTextParagraph
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextParagraphSlice = prismic.SharedSlice<
  "rich_text_paragraph",
  RichTextParagraphSliceVariation
>;

/**
 * Primary content in *Services → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Link field in *Services → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Title field in *Services → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.link_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_title: prismic.KeyTextField;

  /**
   * Title field in *Services → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *Services → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Service Name field in *Services → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_name: prismic.TitleField;

  /**
   * Service Description field in *Services → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_description: prismic.RichTextField;

  /**
   * Service Link field in *Services → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField;

  /**
   * Service Icon field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_icon: prismic.ImageField<never>;

  /**
   * Service Image field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Primary content in *TitleDateAndAuthor → Primary*
 */
export interface TitleDateAndAuthorSliceDefaultPrimary {
  /**
   * Title field in *TitleDateAndAuthor → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: title_date_and_author.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Author field in *TitleDateAndAuthor → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_date_and_author.primary.author
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  author: prismic.RichTextField;

  /**
   * Date field in *TitleDateAndAuthor → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: title_date_and_author.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;
}

/**
 * Default variation for TitleDateAndAuthor Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDateAndAuthorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleDateAndAuthorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleDateAndAuthor*
 */
type TitleDateAndAuthorSliceVariation = TitleDateAndAuthorSliceDefault;

/**
 * TitleDateAndAuthor Shared Slice
 *
 * - **API ID**: `title_date_and_author`
 * - **Description**: TitleDateAndAuthor
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDateAndAuthorSlice = prismic.SharedSlice<
  "title_date_and_author",
  TitleDateAndAuthorSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataHeaderNavigationItem,
      SettingsDocumentDataFooterNavigationItem,
      SettingsDocumentDataSocialLinksItem,
      AllDocumentTypes,
      AccordionSlice,
      AccordionSliceDefaultPrimary,
      AccordionSliceDefaultItem,
      AccordionSliceVariation,
      AccordionSliceDefault,
      AdvisorProfileCardSlice,
      AdvisorProfileCardSliceDefaultPrimary,
      AdvisorProfileCardSliceDefaultItem,
      AdvisorProfileCardSliceVariation,
      AdvisorProfileCardSliceDefault,
      ArticleListSlice,
      ArticleListSliceDefaultPrimary,
      ArticleListSliceDefaultItem,
      ArticleListSliceVariation,
      ArticleListSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceDefaultItem,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FullPageImageSlice,
      FullPageImageSliceDefaultPrimary,
      FullPageImageSliceVariation,
      FullPageImageSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageAndTextSlice,
      ImageAndTextSliceDefaultPrimary,
      ImageAndTextSliceImageAndTextRightPrimary,
      ImageAndTextSliceImageAndTextLeftPrimary,
      ImageAndTextSliceVariation,
      ImageAndTextSliceDefault,
      ImageAndTextSliceImageAndTextRight,
      ImageAndTextSliceImageAndTextLeft,
      RichTextParagraphSlice,
      RichTextParagraphSliceDefaultPrimary,
      RichTextParagraphSliceVariation,
      RichTextParagraphSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
      TitleDateAndAuthorSlice,
      TitleDateAndAuthorSliceDefaultPrimary,
      TitleDateAndAuthorSliceVariation,
      TitleDateAndAuthorSliceDefault,
    };
  }
}
